version: '3'

services:
    ros-melodic-base:
        build:
            context: .
            dockerfile: Dockerfile.base
        image: melodic-base
    
    melodic-kinect:
        build: 
            context: .
            dockerfile: Dockerfile.kinect
            args: 
                - BASE_IMAGE=melodic-base
        image: melodic-kinect