# This is a basic workflow to help you get started with Actions

name: ROS2 Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {USE_CUDA: "", ROS_DISTRO: foxy, tag: $(ROS_DISTRO)-base}
          - {USE_CUDA: "", ROS_DISTRO: galactic, tag: $(ROS_DISTRO)-base}
          - {USE_CUDA: true, ROS_DISTRO: foxy, tag: CUDA$(ROS_DISTRO)-base}
          - {USE_CUDA: true, ROS_DISTRO: galactic, tag: CUDA$(ROS_DISTRO)-base}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: /ros2/Dockerfile
          push: true
          build-args: |
            USE_CUDA=$(USE_CUDA)
            CUDA_VERSION=11.4.0
            UBUNTU_DISTRO=20.04
            ROS_DISTRO=$(ROS_DISTRO)
          tags: ${{ secrets.DOCKER_USERNAME }}/build_env:$(tag)
    
